package com.ti.task_manager.mapper;

import com.ti.task_manager.entities.Mission;
import com.ti.task_manager.entities.MissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Dec 03 21:32:44 CST 2018
     */
    long countByExample(MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Dec 03 21:32:44 CST 2018
     */
    int deleteByExample(MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Dec 03 21:32:44 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Dec 03 21:32:44 CST 2018
     */
    int insert(Mission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Dec 03 21:32:44 CST 2018
     */
    int insertSelective(Mission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Dec 03 21:32:44 CST 2018
     */
    List<Mission> selectByExampleWithBLOBs(MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Dec 03 21:32:44 CST 2018
     */
    List<Mission> selectByExample(MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Dec 03 21:32:44 CST 2018
     */
    Mission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Dec 03 21:32:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") Mission record, @Param("example") MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Dec 03 21:32:44 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Mission record, @Param("example") MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Dec 03 21:32:44 CST 2018
     */
    int updateByExample(@Param("record") Mission record, @Param("example") MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Dec 03 21:32:44 CST 2018
     */
    int updateByPrimaryKeySelective(Mission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Dec 03 21:32:44 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Mission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Mon Dec 03 21:32:44 CST 2018
     */
    int updateByPrimaryKey(Mission record);
}